/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Connection {
  'id' : ConnectionId,
  'username' : [] | [string],
  'datasetId' : DatasetId,
  'host' : [] | [string],
  'password' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'port' : [] | [bigint],
  'filePath' : [] | [string],
  'fileType' : [] | [FileType],
  'sourceLocation' : [] | [SourceLocation],
  'connectionType' : ConnectionType,
  'updatedAt' : bigint,
  'dbName' : [] | [string],
  'dbType' : [] | [DbType],
  'tableName' : [] | [string],
}
export type ConnectionId = bigint;
export type ConnectionType = { 'file' : null } |
  { 'database' : null };
export interface Dataset {
  'id' : DatasetId,
  'subProjectId' : SubProjectId,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'datasetType' : DatasetType,
}
export type DatasetId = bigint;
export type DatasetType = { 'source' : null } |
  { 'target' : null };
export type DbType = { 'db2' : null } |
  { 'mySql' : null } |
  { 'postgres' : null } |
  { 'sqlServer' : null } |
  { 'databricks' : null };
export type FileType = { 'csv' : null } |
  { 'xml' : null } |
  { 'json' : null } |
  { 'fixedWidth' : null } |
  { 'parquet' : null };
export interface JoinConfig {
  'leftConnectionId' : ConnectionId,
  'joinType' : JoinType,
  'rightConnectionId' : ConnectionId,
  'rightKey' : string,
  'leftKey' : string,
}
export type JoinType = { 'full' : null } |
  { 'left' : null } |
  { 'inner' : null } |
  { 'right' : null };
export interface MockData {
  'rows' : Array<Array<string>>,
  'columns' : Array<string>,
}
export type OutputFormat = { 'csv' : null } |
  { 'xml' : null } |
  { 'json' : null } |
  { 'parquet' : null };
export interface Project {
  'id' : ProjectId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'subProjects' : Array<SubProjectId>,
}
export type ProjectId = bigint;
export type SourceLocation = { 'azureBlob' : null } |
  { 'network' : null } |
  { 'local' : null };
export interface SubProject {
  'id' : SubProjectId,
  'name' : string,
  'targetDataset' : DatasetId,
  'createdAt' : bigint,
  'description' : string,
  'sourceDataset' : DatasetId,
  'updatedAt' : bigint,
  'projectId' : ProjectId,
}
export type SubProjectId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addConnection' : ActorMethod<[DatasetId, Connection], ConnectionId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string], ProjectId>,
  'createSubProject' : ActorMethod<[ProjectId, string, string], SubProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConnectionById' : ActorMethod<[ConnectionId], [] | [Connection]>,
  'getDatasetById' : ActorMethod<[DatasetId], [] | [Dataset]>,
  'getMockData' : ActorMethod<[ConnectionId], [] | [MockData]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSubProjects' : ActorMethod<[ProjectId], Array<SubProject>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setFieldSelection' : ActorMethod<[DatasetId, Array<string>], undefined>,
  'setJoinConfig' : ActorMethod<[DatasetId, JoinConfig], undefined>,
  'setOutputFormat' : ActorMethod<[DatasetId, OutputFormat], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];