/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DatasetId = IDL.Nat;
export const ConnectionId = IDL.Nat;
export const FileType = IDL.Variant({
  'csv' : IDL.Null,
  'xml' : IDL.Null,
  'json' : IDL.Null,
  'fixedWidth' : IDL.Null,
  'parquet' : IDL.Null,
});
export const SourceLocation = IDL.Variant({
  'azureBlob' : IDL.Null,
  'network' : IDL.Null,
  'local' : IDL.Null,
});
export const ConnectionType = IDL.Variant({
  'file' : IDL.Null,
  'database' : IDL.Null,
});
export const DbType = IDL.Variant({
  'db2' : IDL.Null,
  'mySql' : IDL.Null,
  'postgres' : IDL.Null,
  'sqlServer' : IDL.Null,
  'databricks' : IDL.Null,
});
export const Connection = IDL.Record({
  'id' : ConnectionId,
  'username' : IDL.Opt(IDL.Text),
  'datasetId' : DatasetId,
  'host' : IDL.Opt(IDL.Text),
  'password' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'port' : IDL.Opt(IDL.Nat),
  'filePath' : IDL.Opt(IDL.Text),
  'fileType' : IDL.Opt(FileType),
  'sourceLocation' : IDL.Opt(SourceLocation),
  'connectionType' : ConnectionType,
  'updatedAt' : IDL.Int,
  'dbName' : IDL.Opt(IDL.Text),
  'dbType' : IDL.Opt(DbType),
  'tableName' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const SubProjectId = IDL.Nat;
export const DatasetType = IDL.Variant({
  'source' : IDL.Null,
  'target' : IDL.Null,
});
export const Dataset = IDL.Record({
  'id' : DatasetId,
  'subProjectId' : SubProjectId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'datasetType' : DatasetType,
});
export const MockData = IDL.Record({
  'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
  'columns' : IDL.Vec(IDL.Text),
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'subProjects' : IDL.Vec(SubProjectId),
});
export const SubProject = IDL.Record({
  'id' : SubProjectId,
  'name' : IDL.Text,
  'targetDataset' : DatasetId,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sourceDataset' : DatasetId,
  'updatedAt' : IDL.Int,
  'projectId' : ProjectId,
});
export const JoinType = IDL.Variant({
  'full' : IDL.Null,
  'left' : IDL.Null,
  'inner' : IDL.Null,
  'right' : IDL.Null,
});
export const JoinConfig = IDL.Record({
  'leftConnectionId' : ConnectionId,
  'joinType' : JoinType,
  'rightConnectionId' : ConnectionId,
  'rightKey' : IDL.Text,
  'leftKey' : IDL.Text,
});
export const OutputFormat = IDL.Variant({
  'csv' : IDL.Null,
  'xml' : IDL.Null,
  'json' : IDL.Null,
  'parquet' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConnection' : IDL.Func([DatasetId, Connection], [ConnectionId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
  'createSubProject' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text],
      [SubProjectId],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConnectionById' : IDL.Func(
      [ConnectionId],
      [IDL.Opt(Connection)],
      ['query'],
    ),
  'getDatasetById' : IDL.Func([DatasetId], [IDL.Opt(Dataset)], ['query']),
  'getMockData' : IDL.Func([ConnectionId], [IDL.Opt(MockData)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSubProjects' : IDL.Func([ProjectId], [IDL.Vec(SubProject)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setFieldSelection' : IDL.Func([DatasetId, IDL.Vec(IDL.Text)], [], []),
  'setJoinConfig' : IDL.Func([DatasetId, JoinConfig], [], []),
  'setOutputFormat' : IDL.Func([DatasetId, OutputFormat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DatasetId = IDL.Nat;
  const ConnectionId = IDL.Nat;
  const FileType = IDL.Variant({
    'csv' : IDL.Null,
    'xml' : IDL.Null,
    'json' : IDL.Null,
    'fixedWidth' : IDL.Null,
    'parquet' : IDL.Null,
  });
  const SourceLocation = IDL.Variant({
    'azureBlob' : IDL.Null,
    'network' : IDL.Null,
    'local' : IDL.Null,
  });
  const ConnectionType = IDL.Variant({
    'file' : IDL.Null,
    'database' : IDL.Null,
  });
  const DbType = IDL.Variant({
    'db2' : IDL.Null,
    'mySql' : IDL.Null,
    'postgres' : IDL.Null,
    'sqlServer' : IDL.Null,
    'databricks' : IDL.Null,
  });
  const Connection = IDL.Record({
    'id' : ConnectionId,
    'username' : IDL.Opt(IDL.Text),
    'datasetId' : DatasetId,
    'host' : IDL.Opt(IDL.Text),
    'password' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'port' : IDL.Opt(IDL.Nat),
    'filePath' : IDL.Opt(IDL.Text),
    'fileType' : IDL.Opt(FileType),
    'sourceLocation' : IDL.Opt(SourceLocation),
    'connectionType' : ConnectionType,
    'updatedAt' : IDL.Int,
    'dbName' : IDL.Opt(IDL.Text),
    'dbType' : IDL.Opt(DbType),
    'tableName' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const SubProjectId = IDL.Nat;
  const DatasetType = IDL.Variant({ 'source' : IDL.Null, 'target' : IDL.Null });
  const Dataset = IDL.Record({
    'id' : DatasetId,
    'subProjectId' : SubProjectId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'datasetType' : DatasetType,
  });
  const MockData = IDL.Record({
    'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
    'columns' : IDL.Vec(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'subProjects' : IDL.Vec(SubProjectId),
  });
  const SubProject = IDL.Record({
    'id' : SubProjectId,
    'name' : IDL.Text,
    'targetDataset' : DatasetId,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sourceDataset' : DatasetId,
    'updatedAt' : IDL.Int,
    'projectId' : ProjectId,
  });
  const JoinType = IDL.Variant({
    'full' : IDL.Null,
    'left' : IDL.Null,
    'inner' : IDL.Null,
    'right' : IDL.Null,
  });
  const JoinConfig = IDL.Record({
    'leftConnectionId' : ConnectionId,
    'joinType' : JoinType,
    'rightConnectionId' : ConnectionId,
    'rightKey' : IDL.Text,
    'leftKey' : IDL.Text,
  });
  const OutputFormat = IDL.Variant({
    'csv' : IDL.Null,
    'xml' : IDL.Null,
    'json' : IDL.Null,
    'parquet' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConnection' : IDL.Func([DatasetId, Connection], [ConnectionId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
    'createSubProject' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text],
        [SubProjectId],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConnectionById' : IDL.Func(
        [ConnectionId],
        [IDL.Opt(Connection)],
        ['query'],
      ),
    'getDatasetById' : IDL.Func([DatasetId], [IDL.Opt(Dataset)], ['query']),
    'getMockData' : IDL.Func([ConnectionId], [IDL.Opt(MockData)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSubProjects' : IDL.Func([ProjectId], [IDL.Vec(SubProject)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setFieldSelection' : IDL.Func([DatasetId, IDL.Vec(IDL.Text)], [], []),
    'setJoinConfig' : IDL.Func([DatasetId, JoinConfig], [], []),
    'setOutputFormat' : IDL.Func([DatasetId, OutputFormat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };