/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Connection {
    id: ConnectionId;
    username?: string;
    datasetId: DatasetId;
    host?: string;
    password?: string;
    name: string;
    createdAt: bigint;
    port?: bigint;
    filePath?: string;
    fileType?: FileType;
    sourceLocation?: SourceLocation;
    connectionType: ConnectionType;
    updatedAt: bigint;
    dbName?: string;
    dbType?: DbType;
    tableName?: string;
}
export interface SubProject {
    id: SubProjectId;
    name: string;
    targetDataset: DatasetId;
    createdAt: bigint;
    description: string;
    sourceDataset: DatasetId;
    updatedAt: bigint;
    projectId: ProjectId;
}
export type SubProjectId = bigint;
export interface MockData {
    rows: Array<Array<string>>;
    columns: Array<string>;
}
export type DatasetId = bigint;
export interface JoinConfig {
    leftConnectionId: ConnectionId;
    joinType: JoinType;
    rightConnectionId: ConnectionId;
    rightKey: string;
    leftKey: string;
}
export type ConnectionId = bigint;
export interface Dataset {
    id: DatasetId;
    subProjectId: SubProjectId;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    datasetType: DatasetType;
}
export type ProjectId = bigint;
export interface Project {
    id: ProjectId;
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    subProjects: Array<SubProjectId>;
}
export enum ConnectionType {
    file = "file",
    database = "database"
}
export enum DatasetType {
    source = "source",
    target = "target"
}
export enum DbType {
    db2 = "db2",
    mySql = "mySql",
    postgres = "postgres",
    sqlServer = "sqlServer",
    databricks = "databricks"
}
export enum FileType {
    csv = "csv",
    xml = "xml",
    json = "json",
    fixedWidth = "fixedWidth",
    parquet = "parquet"
}
export enum JoinType {
    full = "full",
    left = "left",
    inner = "inner",
    right = "right"
}
export enum OutputFormat {
    csv = "csv",
    xml = "xml",
    json = "json",
    parquet = "parquet"
}
export enum SourceLocation {
    azureBlob = "azureBlob",
    network = "network",
    local = "local"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addConnection(datasetId: DatasetId, connection: Connection): Promise<ConnectionId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(name: string, description: string): Promise<ProjectId>;
    createSubProject(projectId: ProjectId, name: string, description: string): Promise<SubProjectId>;
    deleteProject(projectId: ProjectId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getConnectionById(connectionId: ConnectionId): Promise<Connection | null>;
    getDatasetById(datasetId: DatasetId): Promise<Dataset | null>;
    getMockData(connectionId: ConnectionId): Promise<MockData | null>;
    getProjects(): Promise<Array<Project>>;
    getSubProjects(projectId: ProjectId): Promise<Array<SubProject>>;
    isCallerAdmin(): Promise<boolean>;
    setFieldSelection(datasetId: DatasetId, fields: Array<string>): Promise<void>;
    setJoinConfig(datasetId: DatasetId, config: JoinConfig): Promise<void>;
    setOutputFormat(datasetId: DatasetId, format: OutputFormat): Promise<void>;
}
import type { Connection as _Connection, ConnectionId as _ConnectionId, ConnectionType as _ConnectionType, Dataset as _Dataset, DatasetId as _DatasetId, DatasetType as _DatasetType, DbType as _DbType, FileType as _FileType, JoinConfig as _JoinConfig, JoinType as _JoinType, MockData as _MockData, OutputFormat as _OutputFormat, SourceLocation as _SourceLocation, SubProjectId as _SubProjectId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addConnection(arg0: DatasetId, arg1: Connection): Promise<ConnectionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addConnection(arg0, to_candid_Connection_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addConnection(arg0, to_candid_Connection_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createSubProject(arg0: ProjectId, arg1: string, arg2: string): Promise<SubProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubProject(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnectionById(arg0: ConnectionId): Promise<Connection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDatasetById(arg0: DatasetId): Promise<Dataset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockData(arg0: ConnectionId): Promise<MockData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockData(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockData(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getSubProjects(arg0: ProjectId): Promise<Array<SubProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubProjects(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async setFieldSelection(arg0: DatasetId, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFieldSelection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFieldSelection(arg0, arg1);
            return result;
        }
    }
    async setJoinConfig(arg0: DatasetId, arg1: JoinConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setJoinConfig(arg0, to_candid_JoinConfig_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setJoinConfig(arg0, to_candid_JoinConfig_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setOutputFormat(arg0: DatasetId, arg1: OutputFormat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOutputFormat(arg0, to_candid_OutputFormat_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOutputFormat(arg0, to_candid_OutputFormat_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ConnectionType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionType): ConnectionType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Connection_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Connection): Connection {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DatasetType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DatasetType): DatasetType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Dataset_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dataset): Dataset {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_DbType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DbType): DbType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SourceLocation_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceLocation): SourceLocation {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Connection]): Connection | null {
    return value.length === 0 ? null : from_candid_Connection_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileType]): FileType | null {
    return value.length === 0 ? null : from_candid_FileType_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SourceLocation]): SourceLocation | null {
    return value.length === 0 ? null : from_candid_SourceLocation_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DbType]): DbType | null {
    return value.length === 0 ? null : from_candid_DbType_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dataset]): Dataset | null {
    return value.length === 0 ? null : from_candid_Dataset_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MockData]): MockData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConnectionId;
    username: [] | [string];
    datasetId: _DatasetId;
    host: [] | [string];
    password: [] | [string];
    name: string;
    createdAt: bigint;
    port: [] | [bigint];
    filePath: [] | [string];
    fileType: [] | [_FileType];
    sourceLocation: [] | [_SourceLocation];
    connectionType: _ConnectionType;
    updatedAt: bigint;
    dbName: [] | [string];
    dbType: [] | [_DbType];
    tableName: [] | [string];
}): {
    id: ConnectionId;
    username?: string;
    datasetId: DatasetId;
    host?: string;
    password?: string;
    name: string;
    createdAt: bigint;
    port?: bigint;
    filePath?: string;
    fileType?: FileType;
    sourceLocation?: SourceLocation;
    connectionType: ConnectionType;
    updatedAt: bigint;
    dbName?: string;
    dbType?: DbType;
    tableName?: string;
} {
    return {
        id: value.id,
        username: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.username)),
        datasetId: value.datasetId,
        host: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.host)),
        password: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.password)),
        name: value.name,
        createdAt: value.createdAt,
        port: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.port)),
        filePath: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.filePath)),
        fileType: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.fileType)),
        sourceLocation: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.sourceLocation)),
        connectionType: from_candid_ConnectionType_n26(_uploadFile, _downloadFile, value.connectionType),
        updatedAt: value.updatedAt,
        dbName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.dbName)),
        dbType: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.dbType)),
        tableName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.tableName))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DatasetId;
    subProjectId: _SubProjectId;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    datasetType: _DatasetType;
}): {
    id: DatasetId;
    subProjectId: SubProjectId;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    datasetType: DatasetType;
} {
    return {
        id: value.id,
        subProjectId: value.subProjectId,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        datasetType: from_candid_DatasetType_n34(_uploadFile, _downloadFile, value.datasetType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    csv: null;
} | {
    xml: null;
} | {
    json: null;
} | {
    fixedWidth: null;
} | {
    parquet: null;
}): FileType {
    return "csv" in value ? FileType.csv : "xml" in value ? FileType.xml : "json" in value ? FileType.json : "fixedWidth" in value ? FileType.fixedWidth : "parquet" in value ? FileType.parquet : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    azureBlob: null;
} | {
    network: null;
} | {
    local: null;
}): SourceLocation {
    return "azureBlob" in value ? SourceLocation.azureBlob : "network" in value ? SourceLocation.network : "local" in value ? SourceLocation.local : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: null;
} | {
    database: null;
}): ConnectionType {
    return "file" in value ? ConnectionType.file : "database" in value ? ConnectionType.database : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    db2: null;
} | {
    mySql: null;
} | {
    postgres: null;
} | {
    sqlServer: null;
} | {
    databricks: null;
}): DbType {
    return "db2" in value ? DbType.db2 : "mySql" in value ? DbType.mySql : "postgres" in value ? DbType.postgres : "sqlServer" in value ? DbType.sqlServer : "databricks" in value ? DbType.databricks : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: null;
} | {
    target: null;
}): DatasetType {
    return "source" in value ? DatasetType.source : "target" in value ? DatasetType.target : value;
}
function to_candid_ConnectionType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConnectionType): _ConnectionType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Connection_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Connection): _Connection {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DbType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DbType): _DbType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FileType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_JoinConfig_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinConfig): _JoinConfig {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_JoinType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinType): _JoinType {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_OutputFormat_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OutputFormat): _OutputFormat {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_SourceLocation_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceLocation): _SourceLocation {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ConnectionId;
    username?: string;
    datasetId: DatasetId;
    host?: string;
    password?: string;
    name: string;
    createdAt: bigint;
    port?: bigint;
    filePath?: string;
    fileType?: FileType;
    sourceLocation?: SourceLocation;
    connectionType: ConnectionType;
    updatedAt: bigint;
    dbName?: string;
    dbType?: DbType;
    tableName?: string;
}): {
    id: _ConnectionId;
    username: [] | [string];
    datasetId: _DatasetId;
    host: [] | [string];
    password: [] | [string];
    name: string;
    createdAt: bigint;
    port: [] | [bigint];
    filePath: [] | [string];
    fileType: [] | [_FileType];
    sourceLocation: [] | [_SourceLocation];
    connectionType: _ConnectionType;
    updatedAt: bigint;
    dbName: [] | [string];
    dbType: [] | [_DbType];
    tableName: [] | [string];
} {
    return {
        id: value.id,
        username: value.username ? candid_some(value.username) : candid_none(),
        datasetId: value.datasetId,
        host: value.host ? candid_some(value.host) : candid_none(),
        password: value.password ? candid_some(value.password) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        port: value.port ? candid_some(value.port) : candid_none(),
        filePath: value.filePath ? candid_some(value.filePath) : candid_none(),
        fileType: value.fileType ? candid_some(to_candid_FileType_n3(_uploadFile, _downloadFile, value.fileType)) : candid_none(),
        sourceLocation: value.sourceLocation ? candid_some(to_candid_SourceLocation_n5(_uploadFile, _downloadFile, value.sourceLocation)) : candid_none(),
        connectionType: to_candid_ConnectionType_n7(_uploadFile, _downloadFile, value.connectionType),
        updatedAt: value.updatedAt,
        dbName: value.dbName ? candid_some(value.dbName) : candid_none(),
        dbType: value.dbType ? candid_some(to_candid_DbType_n9(_uploadFile, _downloadFile, value.dbType)) : candid_none(),
        tableName: value.tableName ? candid_some(value.tableName) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leftConnectionId: ConnectionId;
    joinType: JoinType;
    rightConnectionId: ConnectionId;
    rightKey: string;
    leftKey: string;
}): {
    leftConnectionId: _ConnectionId;
    joinType: _JoinType;
    rightConnectionId: _ConnectionId;
    rightKey: string;
    leftKey: string;
} {
    return {
        leftConnectionId: value.leftConnectionId,
        joinType: to_candid_JoinType_n39(_uploadFile, _downloadFile, value.joinType),
        rightConnectionId: value.rightConnectionId,
        rightKey: value.rightKey,
        leftKey: value.leftKey
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DbType): {
    db2: null;
} | {
    mySql: null;
} | {
    postgres: null;
} | {
    sqlServer: null;
} | {
    databricks: null;
} {
    return value == DbType.db2 ? {
        db2: null
    } : value == DbType.mySql ? {
        mySql: null
    } : value == DbType.postgres ? {
        postgres: null
    } : value == DbType.sqlServer ? {
        sqlServer: null
    } : value == DbType.databricks ? {
        databricks: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    csv: null;
} | {
    xml: null;
} | {
    json: null;
} | {
    fixedWidth: null;
} | {
    parquet: null;
} {
    return value == FileType.csv ? {
        csv: null
    } : value == FileType.xml ? {
        xml: null
    } : value == FileType.json ? {
        json: null
    } : value == FileType.fixedWidth ? {
        fixedWidth: null
    } : value == FileType.parquet ? {
        parquet: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinType): {
    full: null;
} | {
    left: null;
} | {
    inner: null;
} | {
    right: null;
} {
    return value == JoinType.full ? {
        full: null
    } : value == JoinType.left ? {
        left: null
    } : value == JoinType.inner ? {
        inner: null
    } : value == JoinType.right ? {
        right: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OutputFormat): {
    csv: null;
} | {
    xml: null;
} | {
    json: null;
} | {
    parquet: null;
} {
    return value == OutputFormat.csv ? {
        csv: null
    } : value == OutputFormat.xml ? {
        xml: null
    } : value == OutputFormat.json ? {
        json: null
    } : value == OutputFormat.parquet ? {
        parquet: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceLocation): {
    azureBlob: null;
} | {
    network: null;
} | {
    local: null;
} {
    return value == SourceLocation.azureBlob ? {
        azureBlob: null
    } : value == SourceLocation.network ? {
        network: null
    } : value == SourceLocation.local ? {
        local: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConnectionType): {
    file: null;
} | {
    database: null;
} {
    return value == ConnectionType.file ? {
        file: null
    } : value == ConnectionType.database ? {
        database: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
